---
title: "SURV 727 Final Project"
author: "Mathew Hill"
date: "2024-11-25"
output: pdf_document
---

GitHub link: https://github.com/mathewhill/surv727_final_project

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(gtrendsR)
library(censusapi)
library(ggplot2)
library(dplyr)
```

```{r}
timeframe <- "2022-01-01 2022-12-31"
```

```{r}
trends_low_volume <- gtrends(
  keyword = c("abortion", "abortion pill", "murder", "roe v wade"),
  time = timeframe,
  geo = "US-FL",
  low_search_volume = TRUE
) #using low_search_volume = TRUE for "abortion pill", "murder", "roe v wade"
```

```{r}
trends_high_volume <- gtrends(
  keyword = "abortion",
  time = timeframe,
  geo = "US-FL"
) #Using low_search_volume = FALSE for "abortion"
```

```{r}
city_df_low <- trends_low_volume$interest_by_city %>%
  filter(keyword != "abortion") #excluding abortion from the low search volume df

city_df_high <- trends_high_volume$interest_by_city 
  

combined_city_data <- bind_rows(city_df_low, city_df_high)

head(combined_city_data)
```

```{r}
low_volume_interest <- trends_low_volume$interest_over_time
high_volume_interest <- trends_high_volume$interest_over_time

low_volume_interest <- low_volume_interest %>%
  mutate(hits = as.numeric(hits)) %>%
  filter(keyword != "abortion") 

high_volume_interest <- high_volume_interest %>%
  mutate(hits = as.numeric(hits)) %>%
  filter(keyword == "abortion") 

combined_interest_data <- bind_rows(low_volume_interest, high_volume_interest)

interest_clean <- combined_interest_data %>%
  select(date, keyword, hits) %>%
  filter(!is.na(hits)) 

head(interest_clean)
```

```{r}
interest_clean <- combined_interest_data %>%
  select(date, keyword, hits) %>%
  mutate(hits = as.numeric(hits)) %>%
  filter(!is.na(hits))

ggplot(interest_clean, aes(x = date, y = hits, color = keyword)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Search Trends for Abortion and Related Terms",
    x = "Date", y = "Search Interest",
    color = "Search Term"
  ) +
  theme_minimal()

```

```{r}
abortion_filtered_city_df <- combined_city_data %>%
  filter(keyword == "abortion") #abortion df with cities

abortion_pill_filtered_city_df <- combined_city_data %>%
  filter(keyword == "abortion pill") #abortion df with cities

murder_filtered_city_df <- combined_city_data %>%
  filter(keyword == "murder") #murder df with cities

roe_v_wade_filtered_city_df <- combined_city_data %>%
  filter(keyword == "roe v wade") #roe v wade df with cities
```

```{r}
cs_key <- trimws(read_file("C:/Users/mathe/OneDrive/Documents/census-key.txt"))
#Reading API key from .txt file

census_api_key(cs_key)
```

```{r}
acs_fl <- getCensus(name = "acs/acs5",
                    vintage = 2022,
                    vars = c(
                      "NAME",                #name of the city
                      "B01001_001E",         #total population
                      "B01001_002E",         #total male population
                      "B01001_026E",         #total female population
                      "B02001_002E",         #white 
                      "B02001_003E",         #black
                      "B02001_004E",         #american indian and alaska native
                      "B02001_005E",         #asian
                      "B02001_006E",         #native hawaiian and other pacific islander
                      "B02001_007E",         #some other race alone
                      "B02001_008E",         #two or more races
                      "B06002_001E",         #median age
                      "B19013_001E",         #median household income
                      "B19301_001E"          #income per capita
                    ),
                    region = "place:*",
                    regionin = "state:12",  #florida (state code 12)
                    key = cs_key)         

head(acs_fl)
```

```{r}
acs_fl[acs_fl == -666666666] <- NA 
```

```{r}
acs_fl <- acs_fl %>%
  rename(
    pop = B01001_001E,          #total population
    male = B01001_002E,         #total male population
    female = B01001_026E,       #total female population
    white = B02001_002E,        #white
    black = B02001_003E,        #black 
    native_american = B02001_004E, #american indian and alaska native
    asian = B02001_005E,        #asian
    pacific_islander = B02001_006E, #native hawaiian and other pacific islander
    other_race = B02001_007E,   #other race
    two_or_more = B02001_008E,  #two or more races
    age = B06002_001E,          #median age
    hh_income = B19013_001E,    #median household income
    income = B19301_001E        #income per capita
  )

head(acs_fl)
```

```{r}
acs_fl <- acs_fl %>%
  mutate(
    female_pct = (female / pop) * 100,
    white_pct = (white / pop) * 100,
    black_pct = (black / pop) * 100,
    native_american_pct = (native_american / pop) * 100,
    asian_pct = (asian / pop) * 100,
    pacific_islander_pct = (pacific_islander / pop) * 100,
    other_race_pct = (other_race / pop) * 100,
    two_or_more_pct = (two_or_more / pop) * 100
  )

head(acs_fl)
```

```{r}
acs_fl <- acs_fl %>%
  mutate(
    female_pct = ifelse(pop > 0, (female / pop) * 100, NA),
    white_pct = ifelse(pop > 0, (white / pop) * 100, NA),
    black_pct = ifelse(pop > 0, (black / pop) * 100, NA),
    native_american_pct = ifelse(pop > 0, (native_american / pop) * 100, NA),
    asian_pct = ifelse(pop > 0, (asian / pop) * 100, NA),
    pacific_islander_pct = ifelse(pop > 0, (pacific_islander / pop) * 100, NA),
    other_race_pct = ifelse(pop > 0, (other_race / pop) * 100, NA),
    two_or_more_pct = ifelse(pop > 0, (two_or_more / pop) * 100, NA)
  )
```

```{r}
acs_fl <- acs_fl %>%
  mutate(location = sub(", Florida", "", NAME)) %>%
  mutate(location = trimws(location)) #extracting city names without the state into its own column

head(acs_fl)
```

```{r}
pattern <- " (village|city|town|CDP)$" #removing these endings to cities 

acs_fl_clean <- acs_fl %>%
  mutate(location = gsub(pattern, "", location, ignore.case = TRUE))
#removing above endings for the ACS data

head(acs_fl_clean)
```

```{r}
abortion_combined_data <- acs_fl_clean %>%
  inner_join(abortion_filtered_city_df, by = "location") #combining two data frames
head(abortion_combined_data)
```

```{r}
abortion_pill_combined_data <- acs_fl_clean %>%
  inner_join(abortion_pill_filtered_city_df, by = "location") #combining two data frames
head(abortion_pill_combined_data)
```

```{r}
murder_combined_data <- acs_fl_clean %>%
  inner_join(murder_filtered_city_df, by = "location") #combining two data frames
head(murder_combined_data)
```

```{r}
roe_v_wade_combined_data <- acs_fl_clean %>%
  inner_join(roe_v_wade_filtered_city_df, by = "location") #combining two data frames
head(roe_v_wade_combined_data)
```

```{r}
abortion_combined_data <- abortion_combined_data[!is.na(abortion_combined_data$hits), ]
abortion_pill_combined_data <- abortion_pill_combined_data[!is.na(abortion_pill_combined_data$hits), ]
murder_combined_data <- murder_combined_data[!is.na(murder_combined_data$hits), ]
roe_v_wade_combined_data <- roe_v_wade_combined_data[!is.na(roe_v_wade_combined_data$hits), ]
```

```{r}
ggplot(abortion_combined_data, aes(x = age, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by Average Age",
       x = "Average Age",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_combined_data, aes(x = hh_income, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by Household Income",
       x = "Household Income",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_combined_data, aes(x = black_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by Black Population Percentage",
       x = "Black Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_combined_data, aes(x = white_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by White Population Percentage",
       x = "White Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_combined_data, aes(x = asian_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by Asian Population Percentage",
       x = "Asian Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_combined_data, aes(x = female_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Search in Cities by Female Population Percentage",
       x = "Female Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = age, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by Average Age",
       x = "Average Age",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = hh_income, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by Household Income",
       x = "Household Income",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = black_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by Black Population Percentage",
       x = "Black Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = white_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by White Population Percentage",
       x = "White Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = asian_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by Asian Population Percentage",
       x = "Asian Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(abortion_pill_combined_data, aes(x = female_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Abortion Pill Search in Cities by Female Population Percentage",
       x = "Female Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = age, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by Average Age",
       x = "Average Age",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = hh_income, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by Household Income",
       x = "Household Income",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = black_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by Black Population Percentage",
       x = "Black Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = white_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by White Population Percentage",
       x = "White Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = asian_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by Asian Population Percentage",
       x = "Asian Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```

```{r}
ggplot(roe_v_wade_combined_data, aes(x = female_pct, y = hits)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Roe V Wade Search in Cities by Female Population Percentage",
       x = "Female Population Percentage",
       y = "Hits",
       color = "Country") +
  theme_minimal()
```
